version: "3.2"
services:
  db:
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d notes || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notes
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/data.sql
    ports:
      - "5432:5432"
    networks:
      - default-db

networks:
  default-db:

